remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme  # add this line if it's not already present

title: My theme for the Exercise
description: Time machine theme for GitHub Pages.
show_downloads: false




